POST http://192.168.114.30:5000/panels/N0MtTTEtUjE=/acquire
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjI=/acquire
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjM=/acquire
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjQ=/acquire
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjU=/acquire
{"client-id":"hurl-test"}