POST http://192.168.114.30:5000/score/xyz
Content-Type: application/json
{"client-id":"hurl-test",
"target-panels":["N0MtTTEtUjE=","N0MtTTEtUjI=","N0MtTTEtUjM=","N0MtTTEtUjQ=","N0MtTTEtUjU="],
"isDoubles":false, 
"isTeamEvent":false,
"t1name":"",
"t2name":"",
"t1":{"p1":{"colors":"","firstname":"Juan","flag":"xxxx","lastname":"Carlos"}},
"t2":{"p1":{"colors":"","firstname":"Joe","flag":"yyyyy","lastname":"Boes"}},
"t1serves":true,
"setScores":[{"first":2,"second":0}],
"gameScore":{"first":"40","second":"0"},
"matchStatus":"IN_GAME",
"description":"","authorName":"test","appVersion":"hurl-test","date":1672413885887,"userPlan":"FREE",
"appOS":"Android","matchCreationDate":1672402758432}