POST http://192.168.114.30:5000/score/xyz
Content-Type: application/json
{"client-id":"hurl-test",
"target-panels":["N0MtTTEtUjE=","N0MtTTEtUjI=","N0MtTTEtUjM=","N0MtTTEtUjQ=","N0MtTTEtUjU="],
"isDoubles":false,
"isTeamEvent":true,
"t1name":"TEC Waldau",
"t2name":"TC Reutlingen",
"t1":{"p1":{"colors":"","firstname":"Mario","flag":"","lastname":"González"}},
"t2":{"p1":{"colors":"","firstname":"Freddy","flag":"","lastname":"Portis"}},
"t1serves":null,
"setScores":[{"first":6,"second":2}, {"first":5,"second":7}, {"first":4,"second":6}],
"gameScore":{},
"matchStatus":"FINISHED",
"matchResult":"T2_WON",
"description":"","authorName":"test","appVersion":"hurl-test","date":1672413885887,"userPlan":"FREE",
"appOS":"Android","matchCreationDate":1672402758432}