POST http://192.168.114.30:5000/panels/N0MtTTEtUjE=/release
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjI=/release
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjM=/release
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjQ=/release
{"client-id":"hurl-test"}

POST http://192.168.114.30:5000/panels/N0MtTTEtUjU=/release
{"client-id":"hurl-test"}